name: ci_integration
description: A command-line application for importing CI builds to the Metrics database.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  archive: ^2.0.13
  args: ^1.6.0
  equatable: ^1.1.1
  firedart:
    git:
      url: https://github.com/platform-platform/firedart.git
  http: ^0.12.0+4
  intl: ^0.16.1
  meta: ^1.1.8
  metrics_core:
    path: ../core
  yaml_map:
    git:
      url: https://github.com/Flank/flank-dashboard.git
      path: yaml_map

dev_dependencies:
  api_mock_server:
    git:
      url: https://github.com/Flank/flank-dashboard.git
      path: api_mock_server
  coverage: ^0.14.2
  lint: ^1.1.1
  mockito: ^4.1.1
  test: ^1.14.1
  test_coverage: ^0.5.0
