name: metrics_core
description: A package providing a base implementations for Metrics applications to support code reuse.

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  email_validator: ^1.0.4
  equatable: ^1.1.1
  meta: 1.3.0

dev_dependencies:
  lint: ^1.1.1
  mockito: ^4.1.3
  test: ^1.14.1
