name: functions
version: 1.0.0
publish_to: none

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  clock: 1.0.1
  collection: 1.14.13
  firebase_functions_interop:    
    git:
      url: https://github.com/pulyaevskiy/firebase-functions-interop
      ref: master
  meta: ^1.1.8
  metrics_core:
    path: ../../core    
  
dev_dependencies:
  build_node_compilers: ^0.2.4
  build_runner: ^1.9.0
  lint: ^1.1.1
  mockito: ^4.1.1
  test: ^1.14.1 

dependency_overrides:
  path: 1.7.0
  js: 0.6.2
  firebase_admin_interop:
    git:
      url: https://github.com/platform-platform/firebase-admin-interop.git  
