name: Metrics CI Integrations Actions

on:
  push:
    branches: master
    paths:
      - metrics/ci_integrations/**
      - metrics/core/**

jobs:
  ci-integrations-actions:
    name: CI Integrations Actions
    runs-on: macOS-latest
    timeout-minutes: 60
    steps:
      - name: Notify about building started
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: building_project_started
          client-payload: '{"building_ci_integrations": "true"}'

      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - uses: cedx/setup-dart@v2
        with:
          release-channel: beta
          version: 2.12.0-133.2.beta

      - name: Get dependencies
        run: pub get
        working-directory: metrics/ci_integrations/

      - name: Dart analyze
        run: dartanalyzer . --fatal-infos --fatal-warnings
        working-directory: metrics/ci_integrations/

      - name: Run tests
        run: pub run test_coverage --print-test-output --no-badge
        working-directory: metrics/ci_integrations/

      - name: Download coverage tool
        run: |
          curl -o coverage_coverter -k https://github.com/platform-platform/monorepo/releases/download/coverage-converter-snapshot/coverage_converter_macos -L
          chmod a+x coverage_coverter
        working-directory: metrics/ci_integrations/

      - name: Convert coverage report
        run: ./coverage_coverter lcov -i coverage/lcov.info -o coverage-summary.json
        working-directory: metrics/ci_integrations/

      - name: Export coverage report
        uses: actions/upload-artifact@v2
        with:
          name: coverage_report
          path: metrics/ci_integrations/coverage-summary.json
          if-no-files-found: error

  ci-integrations-build-actions:
    name: CI Integrations Build Actions
    needs: [ ci-integrations-actions ]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        include:
          - os: macos-latest
            output_name: "ci_integrations_macos"
          - os: ubuntu-latest
            output_name: "ci_integrations_linux"
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - uses: cedx/setup-dart@v2
        with:
          release-channel: beta
          version: 2.12.0-133.2.beta

      - name: Get dependencies
        run: pub get
        working-directory: metrics/ci_integrations/

      - name: Build Application
        run: dart2native -o ${{ matrix.output_name }} bin/main.dart
        working-directory: metrics/ci_integrations/

      - name: Generate SHA256 Hash
        run: shasum -a 256 metrics/ci_integrations/${{ matrix.output_name }} > metrics/ci_integrations/${{ matrix.output_name }}.sha256

      - name: Upload SHA256 Hash
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.output_name }}_sha256
          path: metrics/ci_integrations/${{ matrix.output_name }}.sha256
          if-no-files-found: error

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.output_name }}
          path: metrics/ci_integrations/${{ matrix.output_name }}
          if-no-files-found: error

  ci-integrations-publish-actions:
    name: CI Integrations Publish Actions
    needs: [ ci-integrations-build-actions ]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1
          ref: ${{ github.ref }}

      - name: Install GitHub CLI
        run: |
          sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-key C99B11DEB97541F0
          sudo apt-add-repository https://cli.github.com/packages
          sudo apt update
          sudo apt install gh

      - name: Configure GitHub CLI
        run: gh auth login --with-token <<< ${{ secrets.GITHUB_TOKEN }}

      - name: Download MacOS Build
        uses: actions/download-artifact@v2
        with:
          name: ci_integrations_macos
          path: metrics/ci_integrations/

      - name: Download Linux Build
        uses: actions/download-artifact@v2
        with:
          name: ci_integrations_linux
          path: metrics/ci_integrations/

      - name: Download Linux SHA256 Hash
        uses: actions/download-artifact@v2
        with:
          name: ci_integrations_linux_sha256
          path: metrics/ci_integrations/

      - name: Download MacOS SHA256 Hash
        uses: actions/download-artifact@v2
        with:
          name: ci_integrations_macos_sha256
          path: metrics/ci_integrations/

      - name: Delete release
        run: |
          gh release delete ci_integrations-snapshot -y
          git push --delete origin ci_integrations-snapshot

      - name: Create release
        run: gh release create ci_integrations-snapshot metrics/ci_integrations/ci_integrations_macos metrics/ci_integrations/ci_integrations_macos.sha256 metrics/ci_integrations/ci_integrations_linux metrics/ci_integrations/ci_integrations_linux.sha256 --prerelease --title 'CI Integrations snapshot'

  notify-actions:
    name: Notify about building finished
    runs-on: macos-latest
    needs: [ ci-integrations-publish-actions, ci-integrations-actions, ci-integrations-build-actions ]
    if: "always()"
    steps:
      - name: Notify about building the CI integrations
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: building_project
          client-payload: '{"building_ci_integrations": "true"}'
      - name: Send notification to Slack
        if: needs.ci-integrations-publish-actions.result == 'failure' || needs.ci-integrations-actions.result == 'failure' || needs.ci-integrations-build-actions.result == 'failure' || needs.ci-integrations-publish-actions.result == 'cancelled' || needs.ci-integrations-actions.result == 'cancelled' || needs.ci-integrations-build-actions.result == 'cancelled'
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}
          repository: ${{ github.repository }}
          event-type: send_slack_notification
          client-payload: '{"workflow_name": "${{ github.workflow }}", "run_url": "https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"}'
